apiVersion: v1
kind: Service
metadata:
  name: mynodejsapp
  labels:
    app: mynodejsapp
spec:
  ports:
  - port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: mynodejsapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodejsapp
  labels:
    app: mynodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynodejsapp
  template:
    metadata:
      labels:
        app: mynodejsapp
    spec:
      containers:
      - name: mynodejsapp
        image: mynodejsapp
