apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: mynodejsapp
build:
  artifacts:
  - image: mynodejsapp
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - deployment.yaml
portForward:
- resourceType: service
  resourceName: mynodejsapp
  port: 8080
